CREATE TABLE IF NOT EXISTS Utilisateurs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nomUtilisateur VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    motDePasse VARCHAR(255) NOT NULL,
    dateInscription DATETIME DEFAULT CURRENT_TIMESTAMP
);
